### ISSUE TITLE
Add support for GitLab self hosted instances

### ISSUE THREAD

**Issue by Akasiek** [colinlienard/gitlight#266] opened 2024-03-25 09:29 UTC
Hi! I love the design and idea behind GitLight, but at the moment I cannot find a way to log in to my work GitLab account. We use a self-hosted GitLab that has its own domain.

Are there any plans to support self-hosted GitLab instances?

**Comment by colinlienard** [comment] 2024-03-28 16:36
Hi, thanks for the kind words!
I have never used self-hosted GitLab so I don't really know how authentication works, I thought the login was happening on `gitlab.com` even when self-hosted.
I will look into it

**Comment by AlexW00** [comment] 2024-04-04 11:15
Any updates? Would be so awesome.

**Comment by colinlienard** [comment] 2024-04-04 21:10
Working on it!

**Comment by timurguseynov** [comment] 2024-04-06 20:20
@colinlienard that would be really great, thank you :)

**Comment by colinlienard** [comment] 2024-04-08 11:16
Just merged the pr! Could you please test if it works properly @Akasiek @AlexW00 @timurguseynov? (I cannot test myself because I don't have access to a self-hosted GitLab instance)

Please test on the website (https://gitlight.app/login) and not on the desktop app because I have not published a new release yet. You should now be able to enter the url of your GitLab self-hosted instance and a Personal Access Token

**Comment by Akasiek** [comment] 2024-04-08 11:35
![image](https://github.com/colinlienard/gitlight/assets/37307597/cf181d16-43e2-44cf-8129-33c4b1831fe4)

For now it's giving me a validation error. Are you checking for "gitlab" pattern in subdomain?

**Comment by colinlienard** [comment] 2024-04-08 12:36
No, but I was not handling subdomains properly. Now it should be ok @Akasiek

**Comment by colinlienard** [comment] 2024-04-08 19:57
Hmm for the avatar I don't know if I can do anything, I don't think fetching the url of the image with the pat would change something. I will think about it

The "Invalid URL" thing should be fixed, it was the same issue as earlier

**Comment by timurguseynov** [comment] 2024-04-08 21:07
@colinlienard  do you plan to release it as a desktop app)?

**Comment by Akasiek** [comment] 2024-04-09 06:28
The repo was successfully added, but it won't sync. It keeps saying "Syncing...". 

![image](https://github.com/colinlienard/gitlight/assets/37307597/c69d3bc2-01b9-4d3c-a56f-4bb0eb4fe65e)

After refreshing the page, I have a constant loading screen

![image](https://github.com/colinlienard/gitlight/assets/37307597/1e9ca8cf-eb47-48ad-8082-8a435c059b34)

**Comment by Akasiek** [comment] 2024-04-09 06:32
> @colinlienard do you plan to release it as a desktop app)?

Yes. It will be in the next release. Colin will be releasing it soon. At the moment it doesn't work properly, so anyone with a self-hosted GitLab instance should test it.

**Comment by colinlienard** [comment] 2024-04-09 06:53
Sorry for all the issues @Akasiek 
Could you show me the network tab please?

**Comment by Akasiek** [comment] 2024-04-09 07:20
No problem! I'm glad to help. 

![image](https://github.com/colinlienard/gitlight/assets/37307597/5f2cb02a-042b-48b3-ac1f-b1d34480d41c)

I don't see any errors (except the avatar). Our repo's requests have responses.

**Comment by Akasiek** [comment] 2024-04-09 07:50
On LibreWolf (Firefox based browser) console looks like this:

![image](https://github.com/colinlienard/gitlight/assets/37307597/e40993e2-363d-4378-aa43-1f89c6a32dc2) 

I've opened chromium based browser to check and here is the console:

![image](https://github.com/colinlienard/gitlight/assets/37307597/ff24f827-2f71-4f5c-a161-e761a05022f5)

**Comment by colinlienard** [comment] 2024-04-09 19:14
Just commited a fix (hopefully) @Akasiek

If you still have errors, could you also show the stack trace in screenshots please?

**Comment by loan-mgt** [comment] 2024-04-10 07:22
I've just tested this out, works great. The user profile picture wasn't loading at first, a simple F5 fix did the trick

**Comment by Akasiek** [comment] 2024-04-10 12:03
It seems to work now! 

Although the avatars still don't work. I know you haven't paid attention to them. I think that only custom avatars cannot be loaded. The default, randomly generated avatars will load.

**Comment by loan-mgt** [comment] 2024-04-10 13:39
@Akasiek Custom avatar works great for me, like i've said, a simple F5 did the job

But no issues were visible for me, there were no new notifications, but none of my assigned issues were ever displayed. Is this a feature? A bug from self-hosted GitLab?

**Comment by kisstamasj** [comment] 2024-04-17 07:21
hello
first of all this app its great idea, i would happy to use it. Unfortunatly i have an issue with it. I use it with a self-hosted gitlab, after i logged in and added a repo, it couldnt fetch anything. I can see this on the screen:

![image](https://github.com/colinlienard/gitlight/assets/48266482/c403c77d-5817-4746-a5d0-7a6e7d8274fc)

I don't have time right now to fork the repo, and debug deeply, maybe i'm not the only one who facing with this issue. If i will have time I will try to debug, and give more infor about the problem.

**Comment by colinlienard** [comment] 2024-04-17 14:30
Could you please try to reproduce the issue in the browser and then send a screenshot of the console and the network tab to see what the issue is?

I just though that maybe the organization needs to authorize PATs? I'm not sure because I never used GitLab self-hosted

**Comment by kisstamasj** [comment] 2024-04-18 06:16
> Could you please try to reproduce the issue in the browser and then send a screenshot of the console and the network tab to see what the issue is?
> 
> I just though that maybe the organization needs to authorize PATs? I'm not sure because I never used GitLab self-hosted

I got 404 not found response for some fetch request:
![image](https://github.com/colinlienard/gitlight/assets/48266482/ea15bb3e-36e7-4dd4-aac3-d923e9c9642f)

**Comment by kisstamasj** [comment] 2024-04-18 15:44
sorry, forgot the network tab:
![image](https://github.com/colinlienard/gitlight/assets/48266482/a61128e5-b7fb-4432-bdf0-80f9dd2c6692)

![image](https://github.com/colinlienard/gitlight/assets/48266482/3485dbb4-489b-463e-a946-1dd6ddc3441e)

**Comment by colinlienard** [comment] 2024-04-20 17:57
I tried something, could you please retry? I also added a console log

**Comment by kisstamasj** [comment] 2024-04-22 05:51
now it's working :) i had to re connect with the gitlab, but now syncing fine :)

![image](https://github.com/colinlienard/gitlight/assets/48266482/a1f2ef4e-0a24-4246-af34-9877ba3baefc)

If you need any help for testing with a self-hosted gitlab, just let me know. :)

**Comment by colinlienard** [comment] 2024-04-22 18:59
Nice! Thanks

I just published a new release so it will now work in the desktop app

I'm closing this issue since all problems seem to be resolved, thanks to everyone who helped improve the project! And feel free to reopen this issue or create a new one if needed

**Closed by colinlienard** 2024-04-22 18:59 UTC
Labels: feature, svelte-front, svelte-back
